const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({console,document:{addEventListener(){},querySelector(){return null}},window:{addEventListener(){}}});
const source = fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8').replace(/writeAppHistory\("home", true\);\s*restoreSession\(\);\s*$/, '');
vm.runInContext(source,context);
const run = code => vm.runInContext(code,context);
assert.ok(run(`optionsMarkup().includes('data-mode="lote">MOVIMENTOS')`));
assert.ok(!run(`optionsMarkup().includes('MODO LOTE') || optionsMarkup().includes('data-mode="movimentos"')`));
assert.ok(run(`optionsMarkup().includes('public/options/barcode.svg')`));
run(`state.mode='lote';state.batch={...emptyBatchState(),movementType:'entrada',phase:'review',items:[{code:'10300',name:'Saved draft',qty:1,imageUrl:''}]};`);
assert.ok(run(`batchReviewMarkup().includes('https://images.brickset.com/sets/images/10300-1.jpg')`));
assert.equal(run(`state.batch.items[0].qty`),1);
for (const type of ['entrada', 'saida', 'transferencia']) {
 const title = {entrada:'ENTRADA',saida:'SA\u00cdDA',transferencia:'TRANSFER\u00caNCIA'}[type];
 for (const qty of [0, 1, 2, 1]) {
  run(`state.mode='lote';state.batch={...emptyBatchState(),movementType:'${type}',items:${qty ? `[{code:'10300',name:'Test',qty:${qty},imageUrl:'image',locations:[]}]` : '[]'}};`);
  const scan = run('batchScanMarkup()');
  assert.ok(scan.includes(`<p>${title}${qty > 1 ? ' EM LOTE' : ''}</p>`));
  assert.ok(scan.includes(`<h2>Ler ${qty > 1 ? 'conjuntos' : 'conjunto'}</h2>`));
  const conditions = run('batchConditionsMarkup()');
  assert.ok(conditions.includes(`CONCLUIR ${qty > 1 ? 'LOTE' : 'MOVIMENTO'}`));
  assert.ok(conditions.includes(`<h2>${qty > 1 ? 'Condi\u00e7\u00f5es comuns' : 'Condi\u00e7\u00f5es'}</h2>`));
  assert.ok(run('batchResumePromptMarkup()').includes(`${qty > 1 ? 'LOTE' : 'MOVIMENTO'} EM CURSO`));
  if (type !== 'transferencia') assert.ok(run('batchReviewMarkup()').includes(`<h2>Rever ${qty > 1 ? 'lote' : 'movimento'}</h2>`));
 }
}
run(`state.mode='inventario';state.batch={...emptyBatchState(),movementType:'entrada',items:[{code:'10300',qty:1}]};`);
assert.ok(run('batchConditionsMarkup()').includes('CONCLUIR INVENT\u00c1RIO'));
run(`const originalRender=render;render=()=>{};persistBatchDraft=()=>{};showMovementNotice=()=>{};
 state.mode='lote';state.batch={...emptyBatchState(),movementType:'saida',phase:'scan'};
 findSet=code=>({code:code==='11111111'?'100':'200',ean:code,name:'Test'});
 let release;let stockReads=0;
 getLocationStock=async()=>{stockReads++;if(stockReads===1)await new Promise(resolve=>release=resolve);return [{storage:'A',stock:5}];};`);
(async()=>{
 run(`state.query='11111111';const first=addCodeToBatch(state.query);`);
 await Promise.resolve();
 assert.equal(run(`state.query`),'');
 run(`state.query='22222222';const second=addCodeToBatch(state.query);state.query='333';`);
 run(`release()`);
 await run(`Promise.all([first,second])`);
 assert.equal(run(`state.batch.items.length`),2);
 assert.equal(run(`state.query`),'333');
 assert.equal(run(`batchUnitCount()`),2);
 await run(`addCodeToBatch('11111111')`);
 assert.equal(run(`state.batch.items.length`),2);
 assert.equal(run(`batchItemByCode('100').qty`),2);
 assert.equal(run(`batchUnitCount()`),3);
 run(`state.batch={...emptyBatchState(),movementType:'transferencia',phase:'select'};getLocationStock=async()=>[];`);
 assert.equal(await run(`processBatchCode('11111111',true)`),false);
 assert.ok(run(`batchScannerStockWarning.length > 0`));
 assert.equal(run(`state.batch.items.length`),0);
 run(`getLocationStock=async()=>[{storage:'A',stock:1}]`);
 assert.equal(await run(`processBatchCode('11111111',true)`),true);
 assert.equal(run(`batchScannerStockWarning`),'');
 assert.equal(await run(`processBatchCode('11111111',true)`),false);
 assert.ok(run(`batchScannerStockWarning.includes('1 un.')`));
 assert.equal(run(`batchUnitCount()`),1);
 run(`const overlayIcon={innerHTML:''};let warningClass=false;let overlayLabel='';
 const overlay={classList:{toggle(name,value){warningClass=value}},setAttribute(name,value){overlayLabel=value},querySelector(){return overlayIcon},removeAttribute(){}};
 document.querySelector=()=>overlay;window.setTimeout=()=>1;window.clearTimeout=()=>{};
 showScannerSuccessOverlay(()=>{},'No stock');`);
 assert.equal(run('warningClass'),true);
 assert.ok(run('overlayIcon.innerHTML.includes("<svg")'));
 run(`showScannerSuccessOverlay(()=>{})`);
 assert.equal(run('warningClass'),false);
 assert.equal(run('overlayIcon.innerHTML'),String.fromCodePoint(0x2713));
 run(`state.scannerOpen=true;state.mode='lote';batchMarkup=()=>'<p>Updated count</p>';headerMarkup=()=>'';
 updateLotMobileHeaderSummary=()=>{};renderBatchKeypadWindow=()=>{};
 const liveVideo={srcObject:'live-stream'};const content={innerHTML:''};
 const app={innerHTML:'original scanner',querySelector:selector=>selector==='.camera-scanner'?liveVideo:selector==='.app-content'?content:null,insertAdjacentHTML(){}};
 document.querySelector=selector=>selector==='#app'?app:null;originalRender();`);
 assert.equal(run(`app.innerHTML`),'original scanner');
 assert.equal(run(`liveVideo.srcObject`),'live-stream');
 assert.equal(run(`content.innerHTML`),'<p>Updated count</p>');
 console.log('Batch reading tests passed: merged home action, consecutive EANs, pending stock validation, repeat quantities and live camera preservation.');
})().catch(error=>{console.error(error);process.exitCode=1;});
