const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({console,document:{addEventListener(){}},window:{addEventListener(){}}});
const source = fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8').replace(/writeAppHistory\("home", true\);\s*restoreSession\(\);\s*$/, '');
vm.runInContext(source,context);
const run = code => vm.runInContext(code,context);
run(`function movement(qty,cost,origin='',code='100'){const row=[];row[0]=code;row[5]=origin;row[8]=qty;row[13]=cost;return row;}`);
assert.equal(run(`inventoryCosts([movement(2,10),movement(3,15),movement(-4,0),movement(1,20)]).get('100').cost`),16.5);
assert.equal(run(`inventoryCosts([movement(2,10),movement(-2,''),movement(3,20)]).get('100').cost`),20);
assert.equal(run(`inventoryCosts([movement(2,''),movement(3,20)]).get('100').cost`),null);
assert.equal(run(`inventoryCosts([movement(2,0),movement(2,10)]).get('100').cost`),5);
assert.equal(run(`inventoryCosts([movement(2,10),movement(-1,10,'Transferência'),movement(1,10,'Transferência')]).get('100').cost`),10);
assert.equal(run(`inventoryCosts([movement(1,12,'','CUSTOM-12345670')]).get('CUSTOM-12345670').cost`),12);
for(const value of ['',null,undefined,-1,'abc',' '])assert.throws(()=>run(`entryCost(${JSON.stringify(value)})`),/ENTRY_COST_REQUIRED/);
assert.equal(run(`entryCost('12,50')`),12.5);
assert.equal(run(`entryCost('0')`),0);
run(`state.mode='entrada';state.selected={code:'100',name:'Test'};state.movementForm=emptyMovementForm();`);
assert.ok(run(`foundMarkup().includes('data-movement-field="cost"')`));
run(`state.mode='saida'`);
assert.ok(!run(`foundMarkup().includes('data-movement-field="cost"')`));
console.log('Cost tests passed');
run(`function noInvoice(qty,cost,code='100',origin=''){const row=movement(qty,'',origin,code);row[7]='A';row[14]=cost;row[15]='Sem factura';return row;}
 const separated=[movement(2,10),noInvoice(3,20),movement(2,30),noInvoice(-2,20)];`);
assert.equal(run(`inventoryCosts(separated).get('100').cost`),20);
assert.equal(run(`inventoryCosts(separated,'Sem factura').get('100').cost`),20);
assert.equal(run(`inventoryCosts(separated,'Sem factura').get('100').quantity`),1);
assert.equal(run(`inventoryCosts([...separated,noInvoice(-1,20),noInvoice(2,5)],'Sem factura').get('100').cost`),5);
assert.equal(run(`inventoryCosts([...separated,noInvoice(-1,20)],'Sem factura').get('100').cost`),null);
assert.equal(run(`inventoryCosts([noInvoice(2,0),noInvoice(2,10)],'Sem factura').get('100').cost`),5);
assert.equal(run(`locationStockFromRows(separated,'100','Sem factura')[0].stock`),1);
assert.throws(()=>run(`requireInvoice({invoice:''})`),/INVOICE_REQUIRED/);
run(`const billed=movement(4,10);billed[7]='A';const mixed=[billed,noInvoice(2,20)];const split=splitExitAllocations(mixed,'100',[{storage:'A',quantity:3}]);`);
assert.equal(run(`split[0].group`),'Sem factura');
assert.equal(run(`split[0].quantity`),2);
assert.equal(run(`split[1].group`),'Com factura');
assert.equal(run(`split[1].quantity`),1);
assert.equal(run(`split[1].cost`),10);
run(`state.mode='lote';state.batch={...emptyBatchState(),movementType:'saida',phase:'conditions'};`);
assert.ok(!run(`batchConditionsMarkup().includes('data-batch-field="invoice"')`));
assert.ok(run(`batchConditionsMarkup().includes('Colecção') && batchConditionsMarkup().includes('Vault') && batchConditionsMarkup().includes('Venda')`));
(async()=>{
 run(`state.accessToken='test';state.userEmail='test@example.com';state.selected={code:'100',name:'Test'};
 let requests=[];ensureCostColumn=async()=>{};loadMovementStockRows=async()=>separated;
 fetch=async(url,options)=>{requests.push({url,body:JSON.parse(options.body)});return {ok:true,status:200,json:async()=>({})}};
 state.mode='entrada';state.movementForm={...emptyMovementForm(),invoice:'Sem factura',cost:'7.5',storage:'A',qty:'2'};`);
 await run(`appendMovement()`);
 assert.equal(run(`requests[0].body.values[0][16]`),'');
 assert.equal(run(`requests[0].body.values[0][17]`),7.5);
 assert.equal(run(`requests[0].body.values[0][18]`),'Sem factura');
 run(`state.mode='saida';state.movementForm={...emptyMovementForm(),invoice:'Sem factura',qty:'2',allocations:{A:2}};`);
 await assert.rejects(run(`appendMovement()`),/INSUFFICIENT_STOCK/);
 assert.equal(run(`requests.length`),1);
 run(`state.movementForm.qty='1';state.movementForm.allocations={A:1};`);
 await run(`appendMovement()`);
 assert.equal(run(`requests[1].body.values[0][17]`),20);
 assert.equal(run(`requests[1].body.values[0][11]`),-1);
 const rows=run(`transferRows([{code:'100',qty:1,allocations:{A:1}}],{invoice:'Sem factura',storage:'B'},separated,'id','date','user')`);
 assert.ok(rows.every(row=>row[18]==='Sem factura' && row[16]==='' && row[17]===20));
 run(`state.mode='lote';ensureBatchColumnAndCheckDuplicate=async()=>false;
 state.batch={...emptyBatchState(),movementType:'entrada',id:'batch',form:{...emptyMovementForm(),invoice:'Sem factura',storage:'A'},items:[{code:'100',qty:2,cost:8},{code:'CUSTOM-12345670',qty:1,cost:0}]};`);
 run(`state.batch.form.supplierDoc='FT 001-A';`);
 await run(`appendBatchMovements()`);
 assert.ok(run(`requests[2].body.values.every(row=>row[16]==='' && row[18]==='Sem factura')`));
 assert.equal(run(`requests[2].body.values[0][17]`),8);
 assert.equal(run(`requests[2].body.values[1][17]`),0);
 assert.ok(run(`requests[2].body.values.every(row=>row[19]==="'FT 001-A")`));
 assert.equal(run(`supplierDocumentValue({supplierDoc:'00123'})`),"'00123");
 assert.equal(run(`supplierDocumentValue({supplierDoc:''})`),'');
 run(`state.batch.form.invoice=''`);
 await assert.rejects(run(`appendBatchMovements()`),/INVOICE_REQUIRED/);
 assert.equal(run(`requests.length`),3);
 console.log('Invoice costs: independent averages, reset, zero, stock limits and movement columns passed');
})().catch(error=>{console.error(error);process.exitCode=1;});

run(`const displayItem={code:'100',name:'Test',theme:'Icons',year:2024,stock:1,locations:[],invoiceStock:1,noInvoiceStock:0,cost:0,costWithoutInvoice:null,value:20};`);
assert.ok(run(`consultationResultMarkup(displayItem).includes('title="Com factura"')`));
assert.ok(!run(`consultationResultMarkup(displayItem).includes('title="Sem factura"')`));
assert.ok(!run(`consultationResultMarkup(displayItem).includes('0 un.')`));
run(`displayItem.noInvoiceStock=2;displayItem.stock=3`);
assert.ok(run(`consultationResultMarkup(displayItem).includes('title="Sem factura"')`));
assert.equal(run(`(consultationResultMarkup(displayItem).match(/class="consultation-cost-group"/g)||[]).length`),2);
